substitutions:
  _REGION: "us-central1"
  _ZONE: "us-central1-a"
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}
  _HEAD_BRANCH: ${HEAD_BRANCH}


steps:
  # Step 1: Create a GCE VM to run the tests.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "create-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "${_PR_LABELS}" == *"gcb-perf"* ]]; then
          # --- Original Logic Starts Here ---
          gcloud compute instances create gcsfs-perf-test-vm-${_SHORT_BUILD_ID} \
            --project=${PROJECT_ID} \
            --zone=${_ZONE} \
            --machine-type=e2-custom-24-98304 \
            --image-family=debian-11 \
            --image-project=debian-cloud \
            --service-account=${_VM_SERVICE_ACCOUNT} \
            --tags=allow-ssh \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --network-tier=PREMIUM \
            --metadata=enable-oslogin=TRUE
        else
          echo "Skipping create-vm: _PR_LABELS ('${_PR_LABELS}') does not contain 'gcb-perf'."
        fi
    waitFor: ["-"]


  # Step 2: Run the performance tests inside the newly created VM.
  # This step uses 'gcloud compute ssh' to execute a remote script.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "run-tests-on-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "${_PR_LABELS}" == *"gcb-perf"* ]]; then
          set -e
          # Wait for the VM to be fully initialized and SSH to be ready.
          for i in {1..10}; do
            if gcloud compute ssh gcsfs-perf-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --quiet --command="whoami"; then
              break
            fi
            echo "Waiting for VM to become available... (attempt $$i/10)"
            sleep 15
          done
          ENCODED_KEY=$(echo "$$SSH_KEY" | base64 -w 0)


          VM_SCRIPT="
            set -e
            echo '---   SSH on VM complete---'
            mkdir -p ~/.ssh

            # Set up SSH
            echo "$$ENCODED_KEY" | base64 -d > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan github.com > ~/.ssh/known_hosts

            # Install git and python
            sudo apt-get update
            sudo apt-get install -y git python3-pip python3-venv

            # Clone the repository using the SSH URL
            git clone git@github.com:google-partners/tessellations.git
            cd tessellations/benchmarks/proof-of-concept/microbenchmark/gcsfs
            pip install -r requirements.txt
            python3 main.py 8192_objs_gcs_central1 --benchmark init-source-dataset
            python3 main.py 8192_objs_gcs_central1 --benchmark delete
            python3 main.py 8192_objs_gcs_central1 --benchmark rename
          "

          # Execute the script on the VM via SSH.
          gcloud compute ssh gcsfs-perf-test-vm-${_SHORT_BUILD_ID} --zone=${_ZONE} --internal-ip --command="$$VM_SCRIPT"
        else
          echo "Skipping run-tests-on-vm: _PR_LABELS ('${_PR_LABELS}') does not contain 'gcb-perf'."
        fi
    secretEnv: ['SSH_KEY']
    waitFor:
      - "create-vm"


  # --- Cleanup Steps ---

  # Step 3: Delete the GCE VM.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "delete-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "${_PR_LABELS}" == *"gcb-perf"* ]]; then
          gcloud compute instances delete gcsfs-perf-test-vm-${_SHORT_BUILD_ID} \
            --zone=${_ZONE} \
            --quiet
        else
          echo "Skipping delete-vm: _PR_LABELS ('${_PR_LABELS}') does not contain 'gcb-perf'."
        fi
    waitFor:
      - "run-tests-on-vm"

timeout: "3600s" # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: "projects/${PROJECT_ID}/locations/us-central1/workerPools/cloud-build-worker-pool"

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-deploy-key-tessellations-amaloo/versions/latest
    env: 'SSH_KEY'