import os

BENCHMARK_FILTER = os.environ.get("GCSFS_BENCHMARK_FILTER", "")
BENCHMARK_FILE_SIZES_MB_STR = os.environ.get("GCSFS_BENCHMARK_FILE_SIZES", "128")
BENCHMARK_FILE_SIZES_MB = [int(s) for s in BENCHMARK_FILE_SIZES_MB_STR.split(",") if s]
